[package]
name = "freivalds"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.31.0"
ark-ff = "0.3.0"
ark-bls12-381 = "0.3.0"

